# Task 6

In [3]:
import pandas as pd 
students = {
    'Name' : ['amit' , 'neha' , 'Rahul' , 'Sneha' , 'Pooja'],
    'Marks' : [78 , 85 , 90 , 66 , 72 ],

    'Subject' : ['Math' , 'Math','Science','Science' , 'Math']
}

df = pd.DataFrame(students)

In [6]:
# 1. Students who scored more than 75 marks 

df[df['Marks'] > 75]

    Name  Marks  Subject
0   amit     78     Math
1   neha     85     Math
2  Rahul     90  Science

In [8]:
# 2. Student belonging to subject math

df[df['Subject']=='Math']

    Name  Marks Subject
0   amit     78    Math
1   neha     85    Math
4  Pooja     72    Math

In [17]:
# 3. Student who score more than average marks 

avg = df['Marks'].mean()

df[df['Marks'] > avg]

    Name  Marks  Subject
1   neha     85     Math
2  Rahul     90  Science

In [ ]:
# 4. Student who failed (marks < 70)

df[df['Marks'] < 70]

    Name  Marks  Subject
3  Sneha     66  Science