# Task 4

In [ ]:
import pandas as pd 
students = {
    'Name' : ['amit' , 'neha' , 'Rahul' , 'Sneha' , 'Pooja'],
    'Marks' : [78 , 85 , 90 , 66 , 72 ],

    'Subject' : ['Math' , 'Math','Science','Science' , 'Math']
}

    Name  Marks  Subject
0   amit     78     Math
1   neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math

In [8]:
# 1. Convert it into Data Frame 

df = pd.DataFrame(students)

In [10]:
# 2. Print first 3 rows

df.head(3)

    Name  Marks  Subject
0   amit     78     Math
1   neha     85     Math
2  Rahul     90  Science

In [13]:
# 3. print last 2 rows 

df.tail(2)

    Name  Marks  Subject
3  Sneha     66  Science
4  Pooja     72     Math

In [17]:
# 4. Print Dataframe shape and columns names 

print(df.shape)
print(df.columns )

(5, 3)
Index(['Name', 'Marks', 'Subject'], dtype='str')