# Project

In [5]:
import pandas as pd 
import numpy as np 

df = pd.read_csv('youtube.csv' ,encoding='latin1')

## Phase 1 : Understanding The dataset

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1006 entries, 0 to 1005
Data columns (total 29 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   rank                                     1006 non-null   int64
 1   Youtuber                                 1006 non-null   str
 2   subscribers                              1003 non-null   float64
 3   video views                              1006 non-null   float64
 4   category                                 951 non-null    str
 5   Title                                    1006 non-null   str
 6   uploads                                  1006 non-null   int64
 7   Country of origin                        881 non-null    str
 8   Country                                  881 non-null    str
 9   Abbreviation                             881 non-null    str
 10  channel_type                             974 non-null    str
 11  video_views_rank                         1005 non-null   float64
 12  country_rank                             887 non-null    float64
 13  channel_type_rank                        971 non-null    float64
 14  video_views_for_the_last_30_days         949 non-null    float64
 15  lowest_monthly_earnings                  1006 non-null   float64
 16  highest_monthly_earnings                 1006 non-null   float64
 17  lowest_yearly_earnings                   1006 non-null   float64
 18  highest_yearly_earnings                  1006 non-null   float64
 19  subscribers_for_last_30_days             666 non-null    float64
 20  created_year                             1001 non-null   float64
 21  created_month                            994 non-null    str
 22  created_date                             1001 non-null   float64
 23  Gross tertiary education enrollment (%)  880 non-null    float64
 24  Population                               880 non-null    float64
 25  Unemployment rate                        880 non-null    float64
 26  Urban_population                         880 non-null    float64
 27  Latitude                                 880 non-null    float64
 28  Longitude                                880 non-null    float64
dtypes: float64(19), int64(2), str(8)
memory usage: 228.1 KB

In [59]:
df.shape

(1006, 29)

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1006 entries, 0 to 1005
Data columns (total 29 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   rank                                     1006 non-null   int64
 1   Youtuber                                 1006 non-null   str
 2   subscribers                              1003 non-null   float64
 3   video views                              1006 non-null   float64
 4   category                                 951 non-null    str
 5   Title                                    1006 non-null   str
 6   uploads                                  1006 non-null   int64
 7   Country of origin                        881 non-null    str
 8   Country                                  881 non-null    str
 9   Abbreviation                             881 non-null    str
 10  channel_type                             974 non-null    str
 11  video_views_rank                         1005 non-null   float64
 12  country_rank                             887 non-null    float64
 13  channel_type_rank                        971 non-null    float64
 14  video_views_for_the_last_30_days         949 non-null    float64
 15  lowest_monthly_earnings                  1006 non-null   float64
 16  highest_monthly_earnings                 1006 non-null   float64
 17  lowest_yearly_earnings                   1006 non-null   float64
 18  highest_yearly_earnings                  1006 non-null   float64
 19  subscribers_for_last_30_days             666 non-null    float64
 20  created_year                             1001 non-null   float64
 21  created_month                            994 non-null    str
 22  created_date                             1001 non-null   float64
 23  Gross tertiary education enrollment (%)  880 non-null    float64
 24  Population                               880 non-null    float64
 25  Unemployment rate                        880 non-null    float64
 26  Urban_population                         880 non-null    float64
 27  Latitude                                 880 non-null    float64
 28  Longitude                                880 non-null    float64
dtypes: float64(19), int64(2), str(8)
memory usage: 228.1 KB

In [63]:
df.columns

Index(['rank', 'Youtuber', 'subscribers', 'video views', 'category', 'Title',
       'uploads', 'Country of origin', 'Country', 'Abbreviation',
       'channel_type', 'video_views_rank', 'country_rank', 'channel_type_rank',
       'video_views_for_the_last_30_days', 'lowest_monthly_earnings',
       'highest_monthly_earnings', 'lowest_yearly_earnings',
       'highest_yearly_earnings', 'subscribers_for_last_30_days',
       'created_year', 'created_month', 'created_date',
       'Gross tertiary education enrollment (%)', 'Population',
       'Unemployment rate', 'Urban_population', 'Latitude', 'Longitude'],
      dtype='str')

In [37]:
df.describe()

,rank,subscribers,video views,uploads,video_views_rank,country_rank,channel_type_rank,video_views_for_the_last_30_days,lowest_monthly_earnings,highest_monthly_earnings,...,highest_yearly_earnings,subscribers_for_last_30_days,created_year,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude
count,1006.000000,1.003000e+03,1.006000e+03,1006.000000,1.005000e+03,887.000000,971.000000,9.490000e+02,1006.000000,1.006000e+03,...,1.006000e+03,6.660000e+02,1001.000000,1001.000000,880.000000,8.800000e+02,880.000000,8.800000e+02,880.000000,880.000000
mean,497.472167,2.319501e+07,1.112411e+10,9168.335984,5.607670e+05,384.289741,742.311020,1.760978e+08,37034.348489,5.922453e+05,...,7.110327e+06,3.495419e+05,2012.613387,15.712288,63.597273,4.304586e+08,9.258966,2.239747e+08,26.639994,-13.811287
std,288.738758,1.783047e+07,1.424148e+10,34028.189437,1.368886e+06,1227.359768,1938.126477,4.152933e+08,71869.653679,1.148967e+06,...,1.379921e+07,6.131554e+05,4.514131,8.765109,26.095537,4.735536e+08,4.889912,1.550381e+08,20.516025,84.728810
min,1.000000,1.230000e+07,0.000000e+00,0.000000,1.000000e+00,1.000000,1.000000,1.000000e+00,0.000000,0.000000e+00,...,0.000000e+00,1.000000e+00,1970.000000,1.000000,7.600000,2.025060e+05,0.750000,3.558800e+04,-38.416097,-172.104629
25%,247.250000,1.450000e+07,4.281427e+09,194.000000,3.220000e+02,11.000000,26.000000,1.974000e+07,2700.000000,4.340000e+04,...,5.207500e+05,1.000000e+05,2009.000000,8.000000,36.300000,8.313280e+07,5.270000,5.590832e+07,20.593684,-95.712891
50%,498.500000,1.770000e+07,7.751292e+09,726.500000,9.190000e+02,50.000000,65.000000,6.408500e+07,13250.000000,2.117000e+05,...,2.550000e+06,2.000000e+05,2013.000000,16.000000,68.000000,3.282395e+08,8.880000,2.706630e+08,37.090240,-51.925280
75%,748.750000,2.475000e+07,1.357357e+10,2606.500000,3.645000e+03,123.000000,139.000000,1.692420e+08,38125.000000,6.101750e+05,...,7.300000e+06,4.000000e+05,2016.000000,23.000000,88.200000,3.282395e+08,14.700000,2.706630e+08,37.090240,78.962880
max,995.000000,2.450000e+08,2.280000e+11,301308.000000,4.057944e+06,7741.000000,7741.000000,6.589000e+09,850900.000000,1.360000e+07,...,1.634000e+08,8.000000e+06,2022.000000,31.000000,113.100000,1.397715e+09,14.720000,8.429340e+08,61.924110,138.252924

#### Categorical  Columns

In [61]:
df['Country'].value_counts

<bound method IndexOpsMixin.value_counts of 0                      india
1              United States
2              United States
3              United States
4                      India
                ...
1001                     NaN
1002    United Arab Emirates
1003           United States
1004                   India
1005            Saudi Arabia
Name: Country, Length: 1006, dtype: str>

# Phase 2 : Find Quality problem

In [68]:
# missging values 

df.isnull().sum()

rank                                         0
Youtuber                                     0
subscribers                                  3
video views                                  0
category                                    55
Title                                        0
uploads                                      0
Country of origin                          125
Country                                    125
Abbreviation                               125
channel_type                                32
video_views_rank                             1
country_rank                               119
channel_type_rank                           35
video_views_for_the_last_30_days            57
lowest_monthly_earnings                      0
highest_monthly_earnings                     0
lowest_yearly_earnings                       0
highest_yearly_earnings                      0
subscribers_for_last_30_days               340
created_year                                 5
created_month                               12
created_date                                 5
Gross tertiary education enrollment (%)    126
Population                                 126
Unemployment rate                          126
Urban_population                           126
Latitude                                   126
Longitude                                  126
dtype: int64

In [71]:
df[df['created_month'].isnull()]

,rank,Youtuber,subscribers,video views,category,Title,uploads,Country of origin,Country,Abbreviation,...,subscribers_for_last_30_days,created_year,created_month,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude
1,2,YouTube Movies,170000000.0,0.000000e+00,Film & Animation,youtubemovies,1,United States,United States,US,...,NaN,2006.0,NaN,5.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
120,121,Galinha Pintadinha,33800000.0,2.727455e+10,Film & Animation,Galinha Pintadinha,66,Brazil,Brazil,BR,...,200000.0,2006.0,NaN,30.0,51.3,2.125594e+08,12.08,183241641.0,-14.235004,-51.925280
236,237,Chris Brown,25200000.0,1.552057e+10,Music,ChrisBrown,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
416,417,tabii Urdu,19600000.0,8.779730e+09,Entertainment,tabii Urdu,1306,Turkey,Turkey,TR,...,100000.0,2020.0,NaN,17.0,23.9,8.342962e+07,13.49,63097818.0,38.963745,35.243322
418,419,Clash of Clans,19600000.0,3.961318e+09,Gaming,Clash of Clans,674,United States,United States,US,...,NaN,2013.0,NaN,31.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
420,421,DLS News,19400000.0,2.255543e+09,News & Politics,DLS News,4750,India,India,IN,...,100000.0,2017.0,NaN,5.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880
468,469,Good Mythical Morning,18300000.0,8.798045e+09,Entertainment,Goodmythicalmorning,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
508,509,The Game Theorists,17600000.0,3.752347e+09,Gaming,TheGameTheorists,0,Australia,Australia,AU,...,NaN,NaN,NaN,NaN,113.1,2.576660e+07,5.27,21844756.0,-25.274398,133.775136
577,578,Pitbull,16300000.0,1.247571e+10,Music,Pitbull,352,United States,United States,US,...,NaN,2006.0,NaN,5.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
579,580,Technoblade,16300000.0,1.656453e+09,Gaming,Technoblade,989,United States,United States,US,...,200000.0,2013.0,NaN,28.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
735,736,LEGENDA FUNK,14500000.0,2.440718e+09,NaN,LegendaFUNK,0,Brazil,Brazil,BR,...,NaN,NaN,NaN,NaN,51.3,2.125594e+08,12.08,183241641.0,-14.235004,-51.925280
762,763,Harry Styles,14400000.0,5.689224e+09,People & Blogs,harrystyles,0,United States,United States,US,...,NaN,NaN,NaN,NaN,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891

In [83]:
df[df.duplicated()]

,rank,Youtuber,subscribers,video views,category,Title,uploads,Country of origin,Country,Abbreviation,...,subscribers_for_last_30_days,created_year,created_month,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude
995,12,WWE,96000000.0,7.742847e+10,Sports,WWE,70127,United States,United States,US,...,600000.0,2007.0,May,11.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
996,13,Gaming,93600000.0,0.000000e+00,NaN,Gaming,0,NaN,NaN,NaN,...,NaN,2013.0,Dec,15.0,NaN,NaN,NaN,NaN,NaN,NaN
997,39,LooLoo Kids - Nursery Rhymes and Children's Songs,54000000.0,3.231243e+10,Music,LooLoo Kids - Nursery Rhymes and Children's ï¿½,11,NaN,NaN,NaN,...,NaN,2016.0,Nov,29.0,NaN,NaN,NaN,NaN,NaN,NaN
998,40,Ed Sheeran,53500000.0,3.036768e+10,Music,Ed Sheeran,383,United Kingdom,United Kingdom,GB,...,100000.0,2006.0,Aug,8.0,60.0,6.683440e+07,3.85,55908316.0,55.378051,-3.435973
999,41,Infobells - Hindi,53300000.0,3.051617e+10,Education,Infobells - Hindi,577,India,India,IN,...,1600000.0,2014.0,Jun,6.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880
1000,620,MY FAMILY,15700000.0,6.153496e+09,NaN,My Family,150,Singapore,Singapore,SG,...,800.0,2019.0,Dec,3.0,84.8,5.703569e+06,4.11,5703569.0,1.352083,103.819836
1001,779,The Dodo,14200000.0,9.964117e+09,Pets & Animals,Dorukhan Gï¿½ï¿½ï,8,NaN,NaN,NaN,...,5.0,2006.0,Jun,14.0,NaN,NaN,NaN,NaN,NaN,NaN
1002,787,Supercar Blondie,14100000.0,5.405563e+09,Autos & Vehicles,Supercar Blondie,855,United Arab Emirates,United Arab Emirates,AE,...,500000.0,2007.0,Sep,12.0,36.8,9.770529e+06,2.35,8479744.0,23.424076,53.847818
1003,871,Just For Laughs Gags,13300000.0,7.406629e+09,Comedy,Just For Laughs Gags,6916,United States,United States,US,...,100000.0,2007.0,Jan,14.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
1004,872,Kabita's Kitchen,13300000.0,2.831276e+09,Howto & Style,Kabita's Kitchen,1489,India,India,IN,...,NaN,2014.0,Oct,7.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880
1005,873,BanderitaX,13300000.0,4.129249e+09,Gaming,BanderitaX,1640,Saudi Arabia,Saudi Arabia,SA,...,200000.0,2013.0,Aug,20.0,68.0,3.426853e+07,5.93,28807838.0,23.885942,45.079162

In [85]:
df["Country"].unique()

<StringArray>
[               'india',        'United States',                'India',
                    nan,                'Japan',               'Russia',
          'South Korea',       'United Kingdom',               'Canada',
               'Brazil',            'Argentina',                'Chile',
                 'Cuba',          'El Salvador',             'Pakistan',
          'Philippines',             'Thailand',             'Colombia',
             'Barbados',               'Mexico', 'United Arab Emirates',
                'Spain',         'Saudi Arabia',            'Indonesia',
               'Turkey',            'Venezuela',               'Kuwait',
               'Jordan',          'Netherlands',            'Singapore',
            'Australia',                'Italy',              'Germany',
               'France',               'Sweden',          'Afghanistan',
              'Ukraine',               'Latvia',          'Switzerland',
              'Vietnam',             'Malaysia',                'China',
                 'Iraq',                'Egypt',              'Andorra',
              'Ecuador',              'Morocco',                 'Peru',
           'Bangladesh',              'Finland',                'Samoa']
Length: 51, dtype: str

In [97]:
df["Country"].value_counts()

Country
United States           315
India                   169
Brazil                   62
United Kingdom           44
Mexico                   33
Indonesia                28
Spain                    22
Thailand                 18
South Korea              17
Russia                   16
Canada                   15
Argentina                13
Philippines              12
Colombia                 11
Saudi Arabia             10
Australia                 9
United Arab Emirates      8
Ukraine                   8
Pakistan                  6
Germany                   6
Japan                     5
France                    5
Turkey                    4
Singapore                 4
Sweden                    4
Chile                     3
Jordan                    3
Netherlands               3
Vietnam                   3
Italy                     2
Iraq                      2
Egypt                     2
Ecuador                   2
india                     1
Cuba                      1
El Salvador               1
Barbados                  1
Venezuela                 1
Kuwait                    1
Afghanistan               1
Latvia                    1
Switzerland               1
Malaysia                  1
China                     1
Andorra                   1
Morocco                   1
Peru                      1
Bangladesh                1
Finland                   1
Samoa                     1
Name: count, dtype: int64

# phase 3 : clean the dat

In [99]:
df = df.drop_duplicates()
df

,rank,Youtuber,subscribers,video views,category,Title,uploads,Country of origin,Country,Abbreviation,...,subscribers_for_last_30_days,created_year,created_month,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude
0,1,T-Series,245000000.0,2.280000e+11,Music,T-Series,20082,India,india,IN,...,2000000.0,2006.0,Mar,13.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880
1,2,YouTube Movies,170000000.0,0.000000e+00,Film & Animation,youtubemovies,1,United States,United States,US,...,NaN,2006.0,NaN,5.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
2,3,MrBeast,166000000.0,2.836884e+10,Entertainment,MrBeast,741,United States,United States,US,...,8000000.0,2012.0,Feb,20.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
3,4,Cocomelon - Nursery Rhymes,162000000.0,1.640000e+11,Education,Cocomelon - Nursery Rhymes,966,United States,United States,US,...,1000000.0,2006.0,Sep,1.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
4,5,SET India,159000000.0,1.480000e+11,Shows,SET India,116536,India,India,IN,...,1000000.0,2006.0,Sep,20.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,991,Natan por Aï¿,12300000.0,9.029610e+09,Sports,Natan por Aï¿,1200,Brazil,Brazil,BR,...,700000.0,2017.0,Feb,12.0,51.3,2.125594e+08,12.08,183241641.0,-14.235004,-51.925280
991,992,Free Fire India Official,12300000.0,1.674410e+09,People & Blogs,Free Fire India Official,1500,India,India,IN,...,300000.0,2018.0,Sep,14.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880
992,993,Panda,12300000.0,2.214684e+09,NaN,HybridPanda,2452,United Kingdom,United Kingdom,GB,...,1000.0,2006.0,Sep,11.0,60.0,6.683440e+07,3.85,55908316.0,55.378051,-3.435973
993,994,RobTopGames,12300000.0,3.741235e+08,Gaming,RobTopGames,39,Sweden,Sweden,SE,...,100000.0,2012.0,May,9.0,67.0,1.028545e+07,6.48,9021165.0,60.128161,18.643501
994,995,Make Joke Of,12300000.0,2.129774e+09,Comedy,Make Joke Of,62,India,India,IN,...,100000.0,2017.0,Aug,1.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880

In [105]:
# clean the strings 

# df["Country"] = df["Country"].str.strip()

# df["Country"] = df["Country"].str.lower()
# d
df[df['Country'].isnull()]

,rank,Youtuber,subscribers,video views,category,Title,uploads,Country of origin,Country,Abbreviation,...,subscribers_for_last_30_days,created_year,created_month,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude
5,6,Music,119000000.0,0.000000e+00,NaN,Music,0,NaN,NaN,NaN,...,NaN,2013.0,Sep,24.0,NaN,NaN,NaN,NaN,NaN,NaN
12,13,Gaming,93600000.0,0.000000e+00,NaN,Gaming,0,NaN,NaN,NaN,...,NaN,2013.0,Dec,15.0,NaN,NaN,NaN,NaN,NaN,NaN
14,15,Goldmines,86900000.0,2.411823e+10,NaN,goldmines,1,NaN,NaN,NaN,...,NaN,2006.0,Aug,15.0,NaN,NaN,NaN,NaN,NaN,NaN
38,39,LooLoo Kids - Nursery Rhymes and Children's Songs,54000000.0,3.231243e+10,Music,LooLoo Kids - Nursery Rhymes and Children's ï¿½,11,NaN,NaN,NaN,...,NaN,2016.0,Nov,29.0,NaN,NaN,NaN,NaN,NaN,NaN
48,49,Badabun,46800000.0,1.939805e+10,Entertainment,badabun,1,NaN,NaN,NaN,...,75.0,2007.0,Jul,21.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
958,959,Troom Troom PT,12500000.0,4.384178e+09,Howto & Style,Troom Troom PT,2738,NaN,NaN,NaN,...,NaN,2015.0,Apr,19.0,NaN,NaN,NaN,NaN,NaN,NaN
967,968,Troom Troom Indonesia,12500000.0,5.379684e+09,People & Blogs,TROOM TROOM INDONESIA,8,NaN,NaN,NaN,...,NaN,2020.0,Jul,29.0,NaN,NaN,NaN,NaN,NaN,NaN
972,973,Hero Movies 2023,12400000.0,1.689091e+09,People & Blogs,Hero Movies 2023,689,NaN,NaN,NaN,...,NaN,2017.0,Feb,22.0,NaN,NaN,NaN,NaN,NaN,NaN
985,986,TKOR,12400000.0,3.392023e+09,Education,TKoR,0,NaN,NaN,NaN,...,NaN,2006.0,Aug,16.0,NaN,NaN,NaN,NaN,NaN,NaN
986,987,ANNA KOVA,12400000.0,1.395959e+10,People & Blogs,annakova,1,NaN,NaN,NaN,...,NaN,2006.0,Jun,18.0,NaN,NaN,NaN,NaN,NaN,NaN